editor: source

execute:
  cache: false # "Danger, Will Robinson!"
  freeze: false # If you plan to use it, remember to disable it afterward!
  echo: false

project:
  type: book
  output-dir: pdf
  render: [index.qmd]
  pre-render: "R/.pre-render.R"
  post-render: "R/.post-render.R"

filters:
  - latex-environment

commands:
  - legend
  - legendleft

book:
  title: "abnt: Quarto Format for ABNT Theses and Dissertations"
  author: "Daniel Vartanian"
  date: today
  date-format: "YYYY"
  submitted: 2026
  keyword: >-
    ABNT, abntex2, Academic Writing,
    Brazilian Association of Technical Standards,
    Dissertations, LaTeX, Open Science, Quarto, Quarto Format,
    Reproducible Research, Scientific Writing, Templates, Theses
  language: en
  license: "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International"
  publisher: "[University]"
  publisher-place: "[City of university]"
  favicon: images/logo.svg
  url: https://danielvartan.github.io/abnt/
  site-url: https://danielvartan.github.io/abnt/
  repo-url: https://github.com/danielvartan/abnt/
  issue-url: https://github.com/danielvartan/abnt/issues/
  repo-branch: main
  chapters:
    - index.qmd
    - qmd/development.qmd
    - qmd/conclusion.qmd
    - qmd/glossary.qmd
  appendices:
    - qmd/appendix-1.qmd
    - qmd/annex-1.qmd
    - qmd/settings.qmd

format:
  abnt-pdf:
    lang: en # [en, pt-br, es, fr] (for hyphenation)
    babel-lang: english # [english, brazil, spanish, french]
    other-babel-lang: # Do not repeat 'babel-lang' here.
      - french
      - spanish
      - brazil
    papersize: a4 # [a4, a5]
    sides: oneside # [oneside, twoside]
    mainfont: Noto-Sans
    sansfont: Noto-Sans
    monofont: Noto-Sans-Mono
    fontsize: 12pt
    linestretch: 1.5
    parindent: 1cm
    parskip: 0ex
    frenchspacing: true
    biblatexoptions:
      - backend=biber
      - url=true
      - useprefix=false
      - giveninits=true
      - style=abnt
    bibhang: 0cm # Use 0.5cm if `style=apa`.
    bibparsep: -2ex # Use 1ex `style=apa`.
    biblio-footnote: >
      According to the Brazilian Association of Technical Standards
      (ABNT NBR 6023).
    index-page: true
    colorlinks: true
    linkcolor: blue
    filecolor: blue
    citecolor: blue
    urlcolor: blue
    location: "[City]"
    supervisor: "[Supervisor's full name]"
    cosupervisor: "[Co-supervisor's full name]"
    academic-title: "[Master/PhD]"
    academic-degree: "[Master of Science/Doctor of Science]"
    type-of-work: "[Dissertation/Thesis]"
    area-of-concentration: "[Area of concentration]"
    university: "[University]"
    school: "[School/Department]"
    program: "[Graduate program]"
    version-note: "[Original/Revised version]"
    include-in-header: "tex/include-in-header.tex"
    include-before-body: "tex/include-before-body.tex"
    include-after-body: "tex/include-after-body.tex"

citation:
  type: software
  doi: "10.5281/zenodo.18357083"
  url: https://danielvartan.github.io/abnt/

google-scholar: true
bibliography: references.bib
